runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /tasks/.*
  script: main.app

- url: /webhook
  script: main.app

- url: /rest/.*
  script: main.app

- url: /(.+)
  static_files: app/\1
  upload: app/.*

- url: /
  static_files: app/index.html
  upload: app/index.html


